resources:
  - ../namespace.yaml

helmCharts:
  - name: promtail
    repo: https://grafana.github.io/helm-charts
    releaseName: promtail
    namespace: observability
    valuesFile: values.yaml
    version: 6.3.0
