# permissions for end users to edit verrazzanofleets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: verrazzanofleet-editor-role
rules:
- apiGroups:
  - addons.cluster.x-k8s.io
  resources:
  - verrazzanofleets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - addons.cluster.x-k8s.io
  resources:
  - verrazzanofleets/status
  verbs:
  - get
