# permissions for end users to view verrazzanofleets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: verrazzanofleet-viewer-role
rules:
- apiGroups:
  - addons.cluster.x-k8s.io
  resources:
  - verrazzanofleets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - addons.cluster.x-k8s.io
  resources:
  - verrazzanofleets/status
  verbs:
  - get
