# permissions for end users to edit verrazzanoreleases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: verrazzanorelease-editor-role
rules:
- apiGroups:
  - addons.cluster.x-k8s.io
  resources:
  - verrazzanoreleases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - addons.cluster.x-k8s.io
  resources:
  - verrazzanoreleases/status
  verbs:
  - get
