helmCharts:
  - name: kube-state-metrics
    repo: https://prometheus-community.github.io/helm-charts
    namespace: observability
    releaseName: kube-state-metrics
    valuesFile: values.yaml
    version: 4.18.0
